
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/symfony
    ports:
      - "9010:9000"
    depends_on:
      - database

  database:
    image: postgres:14
    container_name: symfony_db
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./Docker/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/symfony
    depends_on:
      - app

volumes:
  db-data:
